---
- hosts: '{{hostlist}}'
  gather_facts: false
  become: yes
  tasks:
   - name: Install maven
     become: yes
     apt: 
       pkg: maven 
       state: latest 
       update_cache: yes 
       cache_valid_time: 3600